### ISSUE TITLE
TimeCode Drop Frame Variation Between Mac CLI and Javascript Version

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaConch_SourceCode#759] opened 2023-07-12 12:44 UTC
Hi Jerome,

We have an issue with the Drop Frame flag in the javascript version. In this version, you'll see that the TimeCode_DropFrame is not being pulled. https://old.mediaarea.net/download/snapshots/binary/libmediaconch0/20230616/. We also tried the latest snapshot here and had the same results https://mediaarea.net/download/snapshots/binary/libmediaconch0/20230712/. 

> <policy name="TimeCode Notation" type="or" rules_run="2" pass_count="0" info_count="0" warn_count="0" fail_count="2" outcome="fail">
                            <policy name="23.98" type="and" rules_run="3" pass_count="1" info_count="0" warn_count="0" fail_count="2" outcome="fail">
                                <rule name="Time code Non Drop Frame" value="TimeCode_DropFrame" tracktype="Other" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:TimeCode_DropFrame" requested="No" actual="" outcome="fail"/>
                                <rule name="FrameRate Numerator" value="FrameRate_Num" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Num" requested="24000" actual="30000" outcome="fail"/>
                                <rule name="FrameRate Denominator" value="FrameRate_Den" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Den" outcome="pass"/>
                            </policy>
                            <policy name="29.97" type="and" rules_run="3" pass_count="2" info_count="0" warn_count="0" fail_count="1" outcome="fail">
                                <rule name="Time code Drop Frame_copy" value="TimeCode_DropFrame" tracktype="Other" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:TimeCode_DropFrame" requested="Yes" actual="" outcome="fail"/>
                                <rule name="FrameRate Numerator" value="FrameRate_Num" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Num" outcome="pass"/>
                                <rule name="FrameRate Denominator" value="FrameRate_Den" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Den" outcome="pass"/>
                            </policy>
                        </policy>

Here is the same report from my MAC cli running MediaConch Command Line Interface 23.03.20230616

> <policy fail_count="1" info_count="0" name="TimeCode Notation" outcome="pass" pass_count="1" rules_run="2" type="or" warn_count="0">
              <policy fail_count="2" info_count="0" name="23.98" outcome="fail" pass_count="1" rules_run="3" type="and" warn_count="0">
                <rule actual="Yes" name="Time code Non Drop Frame" occurrence="1" operator="=" outcome="fail" requested="No" tracktype="Other" value="TimeCode_DropFrame" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:TimeCode_DropFrame"/>
                <rule actual="30000" name="FrameRate Numerator" occurrence="*" operator="=" outcome="fail" requested="24000" tracktype="Video" value="FrameRate_Num" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Num"/>
                <rule name="FrameRate Denominator" occurrence="*" operator="=" outcome="pass" tracktype="Video" value="FrameRate_Den" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Den"/>
              </policy>
              <policy fail_count="0" info_count="0" name="29.97" outcome="pass" pass_count="3" rules_run="3" type="and" warn_count="0">
                <rule name="Time code Drop Frame_copy" occurrence="1" operator="=" outcome="pass" tracktype="Other" value="TimeCode_DropFrame" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:TimeCode_DropFrame"/>
                <rule name="FrameRate Numerator" occurrence="*" operator="=" outcome="pass" tracktype="Video" value="FrameRate_Num" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Num"/>
                <rule name="FrameRate Denominator" occurrence="*" operator="=" outcome="pass" tracktype="Video" value="FrameRate_Den" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Den"/>
              </policy>
            </policy>

Related to this issue and trying to understand versions across javascript and cli, do you think the XML reports could contain the version of MediaConch that was run somewhere so that it is present in the reports. I had to go and ask the team what version of javascript they were running in order to figure out if this was a version mismatch.

**Comment by joe-sciame-wm** [comment] 2023-07-14 00:55
@JeromeMartinez  Any update on this one?

**Comment by JeromeMartinez** [comment] 2023-07-14 13:22
We can not reproduce the issue, please share a sample file demonstrating this issue.

>  do you think the XML reports could contain the version of MediaConch 

We do it for MediaInfo but forgot to do it for MediaConch. @g-maxime please update the XML output wiht MC version.

**Comment by joe-sciame-wm** [comment] 2023-07-14 15:24
Thanks! I'll send you an Aspera link with the file.

**Comment by joe-sciame-wm** [comment] 2023-07-19 17:07
@JeromeMartinez Sending an Aspera link with the media to download. Let me know if you still can't recreate it.

**Comment by joe-sciame-wm** [comment] 2023-07-19 18:03
@JeromeMartinez You should have the package. This is blocking our production launch of the mediaconchjs.

**Comment by g-maxime** [comment] 2023-07-20 09:32
I've tested your file with the demo JavaScript page, and the rule passes with this simplified policy:
```
<policy type="and" name="TimeCode DropFrame">
  <rule name="TimeCode DropFrame" value="TimeCode_DropFrame" tracktype="Other" occurrence="1" operator="=">Yes</rule>
</policy>
```
What JavaScript engine and version do you use (web browser, node)?"

**Comment by joe-sciame-wm** [comment] 2023-07-20 17:28
@JeromeMartinez I sent you the policy we are testing.

**Comment by joe-sciame-wm** [comment] 2023-07-20 20:43
@JeromeMartinez comments from dev team.

Our build pipelines have the following:
node: 16.19.1
npm: 8.19.3
Our local setup:
node: 18.12.1
npm: 8.19.2
Usage
We use the javascript files in a browser-based implementation
Same results for:
Chrome
Edge
Firefox
e.g. We do not use the javascript via a node cli, etc...

Observed
Addition of the two headers: creatingApplication, creatingLibrary

I noticed in latest snapshot test that the dev team run the value is returning now. Checking with them on the file.

```
<policy name="TimeCode Notation" type="or" rules_run="2" pass_count="0" info_count="0" warn_count="0" fail_count="2" outcome="fail">
              <policy name="23.98" type="and" rules_run="3" pass_count="2" info_count="0" warn_count="0" fail_count="1" outcome="fail">
                <rule name="Time code Non Drop Frame" value="TimeCode_DropFrame" tracktype="Other" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:TimeCode_DropFrame" outcome="pass"/>
                <rule name="FrameRate Numerator" value="FrameRate_Num" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Num" requested="24000" actual="30000" outcome="fail"/>
                <rule name="FrameRate Denominator" value="FrameRate_Den" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Den" outcome="pass"/>
              </policy>
              <policy name="29.97" type="and" rules_run="3" pass_count="2" info_count="0" warn_count="0" fail_count="1" outcome="fail">
                <rule name="Time code Drop Frame_copy" value="TimeCode_DropFrame" tracktype="Other" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:TimeCode_DropFrame" requested="Yes" actual="No" outcome="fail"/>
                <rule name="FrameRate Numerator" value="FrameRate_Num" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Num" outcome="pass"/>
                <rule name="FrameRate Denominator" value="FrameRate_Den" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Den" outcome="pass"/>
              </policy>
            </policy>
```

**Comment by joe-sciame-wm** [comment] 2023-07-20 20:56
@JeromeMartinez So release starting with 20230712, the value is filled in but it appears to be flipped. Its reporting "No" when it should be reporting Yes.

20230616: Reporting empty string vs Yes/No
20230712: Reporting No when it should be reporting Yes.
Latest: Reporting No when it should be reporting Yes.

No issues from CLI or GUI

**Comment by g-maxime** [comment] 2023-07-21 14:33
I cannot reproduce the value inversion problem with the provided policy and file:
```
<policy name="23.98" type="and" rules_run="2" pass_count="1" info_count="0" warn_count="0" fail_count="1" outcome="fail">
  <rule name="Time code Non Drop Frame" value="TimeCode_DropFrame" tracktype="Other" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:TimeCode_DropFrame" requested="No" actual="Yes" outcome="fail"/>
  <policy name="FrameRate" type="or" rules_run="2" pass_count="1" info_count="0" warn_count="0" fail_count="1" outcome="pass">
      <rule name="FrameRate Denominator" value="FrameRate_Den" tracktype="Video" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][1]/mi:FrameRate_Den" requested="1001" actual="1001" outcome="pass"/>
      <rule name="FrameRate Numerator" value="FrameRate_Num" tracktype="Video" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][1]/mi:FrameRate_Num" requested="24000" actual="30000" outcome="fail"/>
  </policy>
</policy>
<policy name="29.97" type="and" rules_run="3" pass_count="3" info_count="0" warn_count="0" fail_count="0" outcome="pass">
  <rule name="Time code Drop Frame" value="TimeCode_DropFrame" tracktype="Other" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:TimeCode_DropFrame" requested="Yes" actual="Yes" outcome="pass"/>
  <rule name="FrameRate Numerator" value="FrameRate_Num" tracktype="Other" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:FrameRate_Num" requested="30000" actual="30000" outcome="pass"/>
  <rule name="FrameRate Denominator" value="FrameRate_Den" tracktype="Other" occurrence="1" operator="=" xpath="mi:MediaInfo/mi:track[@type='Other'][1]/mi:FrameRate_Den" requested="1001" actual="1001" outcome="pass"/>
</policy>
```

Tested with the demo (HowToUse.html) page.

Which MediaInfoLib version is reported in the <writingLibrary> tag with the snapshot from my previous message?

**Comment by joe-sciame-wm** [comment] 2023-07-25 00:46
Latest is reporting 

 <creatingApplication version="23.07.20230720" url="https://mediaarea.net/MediaConch">MediaConch</creatingApplication>
  <creatingLibrary version="23.07.20230720" url="https://mediaarea.net/MediaInfo">MediaInfoLib</creatingLibrary>

**Comment by JeromeMartinez** [comment] 2023-07-26 01:45
@joe-sciame-wm we still can not reproduce your issue, could you give access to a basic setup reprodiucing the issue?
[here](https://mediaarea.net/temp/policy-checker/HowToUse.html) is our [latest version](https://mediaarea.net/download/snapshots/binary/libmediaconch0/20230722/MediaConch_DLL_23.07.20230722_JavaScript.zip) online and it seems to work as expected.

**Comment by rgodfreyDisco** [comment] 2023-07-26 14:30
@JeromeMartinez I unfortunately don't think there's any way for me to grant you access to our app. But I did try your policy checker and that passed the our file.

Do you have a sample implementation using the js library that I can use as a tutorial of sorts?

**Comment by JeromeMartinez** [comment] 2023-07-26 23:35
> Do you have a sample implementation using the js library that I can use as a tutorial of sorts?

The policy checker pointed above and its source code also pointed are our sample implementation using the js library that you can use as a tutorial, what is missing from it?

As it works with our tutorial, there is a difference somewhere between our tutorial and your implementation, but without being able to check your code we can not advice more there, you need to catch what difference in your code creates a change of behavior in the MediaConch library.

**Comment by rgodfreyDisco** [comment] 2023-07-27 15:35
@JeromeMartinez I just sent the implementation source through aspera

**Comment by JeromeMartinez** [comment] 2023-07-31 13:50
@rgodfreyDisco so issue is in MediaInfo initial parsing, but we can not reproduce the issue with our example and also we don't find any misusage of the lib with the code extract you provided but we can not run it so we can not do any test with it.

I currently see 2 paths for resolving this issue:
1/ you can do a step by step integration of the lib from our example to your method, and catch when the behavior of the lib changes, and indicates what changes. Not 100% sure we can resolve it if it is far in your integration without possibility to have a standalone demo but it gives a hint about the integration issue.
2/ we provide a lib with some debug code, you test and send the MediaInfo output (it will contain some debug lines), and we repeat until we catch the issue in our code. It may be long on both sides but it permits to dig up to the issue in our code.

**Comment by rgodfreyDisco** [comment] 2023-08-01 15:05
@JeromeMartinez I did some more digging and was able to find that the issue has something to do with the Aspera plugin that we're using. I'm able to get it to pass if I just use a regular html file input but it fails when getting chunks of the file using Aspera.

There are some oddities in the MediaConch methods that are used to loop through the file that I'd like to share.

When looping through the file with a chunk size of `1048576`, the seekTo variable is getting set to `5299985024` by the `checker.checkBufferGoToGet();` method after the first loop. Additionally, the size of the second blob in the loop method ends up being `4` instead of the expected chunk size of `1048576`. I just wanted to make sure this is expected behavior.

There are some differences between the blob sizes when using the Aspera plugin vs the fileInput. The size of the second chunk when using Aspera ends up being `1048576` which is why the previous developer added a conditional when looping to mimic the behavior when using a normal fileInput `chunkSize: loopCount === 2 ? 4 : CHUNK_SIZE`

I'm not sure how to proceed from here and would be open to you guys sending us some code to debug this.

```
normal html file input
	loop 1 
		blob size: 1048576
		seekTo & new offset: 5299985024
	loop 2
		blob size: 4
		seekTo & new offset: 1048576
	loop 3
		blob size: 1048576
		seekTo & new offset: 8539856
	loop 4
		blob size: 1048576
		seekTo & new offset: -1
	
Aspera file input
	loop 1 
		blob size: 1048576
		seekTo & new offset: 5299985024
	loop 2
		blob size: 1048576
		seekTo & new offset: 1048576
	loop 3
		blob size: 1048576
		seekTo & new offset: -1
	
Aspera file input with hard coded size of 4 on second loop
	loop 1 
		blob size: 1048576
		seekTo & new offset: 5299985024
	loop 2
		blob size: 4
		seekTo & new offset: 1048576
	loop 3
		blob size: 1048576
		seekTo & new offset: 8539856
	loop 4
		blob size: 1048576
		seekTo & new offset: -1

```

**Comment by g-maxime** [comment] 2023-08-01 16:06
Second blob size is 4 because MediaInfo requested chunk at EOF-4, with the file you provided (file size is 5298673380):
```
Loop 1:
    Size: 1048576 GoTo: 5298673376
Loop 2:
    Size:       4 GoTo: 1048576
Loop 3:
    Size: 1048576 GoTo: 8190464
Loop 4:
    Size: 1048576 GoTo: 15866912
Loop 5:
    Size: 1048576 GoTo: -1
```
This behavior does not need to be hardcoded.


Weird that Aspera API  returns so much data at this offset.

**Comment by rgodfreyDisco** [comment] 2023-08-01 17:19
I just did a test to compare the blobs from a fileInput tag to the blobs output from Aspera. The blobs produced in the 1st, 3rd, and 4th loops are equal but the blobs produced in the 2nd loop are not equal. I'm not sure how to compare them in a way to make sense of the differences

**Comment by JeromeMartinez** [comment] 2023-08-03 09:07
> The size of the second chunk when using Aspera ends up being 1048576 which is why the previous developer added a conditional when looping to mimic the behavior when using a normal fileInput chunkSize: loopCount === 2 ? 4 : CHUNK_SIZE

Do not do that.
By luck it works (more or less) with this file, but it may not work with another one (in practice e.g. when `moov` atom is at the end of the file).

MediaInfo considers more data then file size as incorrect file size (it trusts more more data input than file size tip) so "Aspera file input" part in your listing has too much data. I am wondering what is the 1048576 byte in "loop 2" has you seek to end less 4 bytes, can you say what you send to MediaInfo with the 1048576 minus 4 bytes after end of files?
This leads me to think that you do not really seek in Aspera so you provide the next 1048576 bytes, can you check that you really seek and provide the last 4 bytes?

If you really seek and provide 4 last bytes + 1048576 minus 4 bytes of garbage, my recommendation is something like "chunkSize: loopCount === 2 ? 4 : CHUNK_SIZE" replaced by "chunkSize: FileSize - FileOffset > CHUNK_SIZE ? FileSize - FileOffset : CHUNK_SIZE"
But really, in my opinion you need to double check that you really seek, because Aspera should not provide more data that real data, I guess that there is an issue there.

> but the blobs produced in the 2nd loop are not equal. I'm not sure how to compare them in a way to make sense of the differences

Are the first 4 bytes in the Aspera content of your loop 2 are really the last 4 bytes of your file?

I didn't understand if "Aspera file input with hard coded size of 4 on second loop" test is fine for the MediaInfo (so MediaConch). I understand that important (loop 1, 3, 4) data is same so I expect that it is.

**Comment by JeromeMartinez** [comment] 2023-08-28 09:22
@rgodfreyDisco @joe-sciame-wm how is it?

**Comment by rgodfreyDisco** [comment] 2023-08-29 13:31
@JeromeMartinez The issue was confirmed to be a bug in Aspera where there is an int overflow for offsets in files over 4gb. It's probably safe to close this MediaConch issue. Thank you for your help on this.

Here's the aspera issue in case you're interested.
https://github.com/IBM/aspera-connect-sdk-js/issues/49#issuecomment-1687060091

**Comment by JeromeMartinez** [comment] 2023-08-29 13:35
Thanks for the feedback, it makes more sense now about the MI behavior.
But for avoiding any unexpected behavior in the future with some file, don't forget to replace "chunkSize: loopCount === 2 ? 4 : CHUNK_SIZE" code if not yet done, it is still not correct and work only with some files by luck.

**Closed by JeromeMartinez** 2023-08-29 13:35 UTC

**Comment by rgodfreyDisco** [comment] 2023-08-29 13:42
Thanks for the reminder, that was one of the first things I changed lol
